### ISSUE TITLE
Symfony 3

### ISSUE THREAD

**Issue by kironet** [BeSimple/BeSimpleI18nRoutingBundle#100]
Are you planning to upgrade this bundle to SF3?

**Comment by aistis-** [comment]
Hi there, it is already compatible!

Use `besimple/i18n-routing-bundle` v2.4 (beta, but quite stable)

**Comment by kironet** [comment]
Nice, to install beta I should require what?
"besimple/i18n-routing-bundle": "2.4"

**Comment by boekkooi** [comment]
Thanks for for responding @aistis- :smile:
