### ISSUE TITLE
The "router" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0

### ISSUE THREAD

**Issue by adrienfr** [BeSimple/BeSimpleI18nRoutingBundle#107]
Q | A
-- | --
Bug report? | yes
Feature request? | no
BC Break report? | no
RFC? | yes/no
Symfony version | 3.4

I got the following deprecation after updating to Symfony 3.4:

> User Deprecated: The "router" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead.

As stated [here](https://github.com/schmittjoh/JMSI18nRoutingBundle/issues/216) and [here](https://github.com/symfony/symfony/issues/25328), router is public, so should be its aliases.

**Comment by thomas2411** [comment]
+1
