### ISSUE TITLE
Same urls for different locales

### ISSUE THREAD

**Issue by smottt** [BeSimple/BeSimpleI18nRoutingBundle#19]
I have 3 separate domains, all with different default locales set in config.yml.

In some cases i18n urls are the same.

When that happens, the default locale gets overwritten with the route locale.

How to reproduce:

* example.si domain - default_locale: sl
* example.hr domain - default_locale: hr
* example.rs domain - default_locale: sr

routing.yml:

```
test:
    locales:  { sl: "/sl-test", hr: "/test", sr: "/test" }
    defaults: { _controller: 'Acme:DemoBundle:test' }
```

Now if you visit example.si/sl-test it chooses the correct "sl" locale. But if you visit example.rs/test it will change its default locale from "sr" to "hr".

**Comment by cordoval** [comment]
exactly, can you please close this ticket @smottt ?
