### ISSUE TITLE
Question: Support for custom defined locale

### ISSUE THREAD

**Issue by jwaterfaucett** [BeSimple/BeSimpleI18nRoutingBundle#24]
Just wondering if the bundle already does support or can support custom locale definitions ie. en_GB for british english and,
en_US for english or de_DE, etc. 

This would be a great feature to be able to see in the url.

Thanks in advance 

P.S. this bundle is a must for all those dealing with tons of languages daily, ie. more than two in a single site, the hundreds of duplicate routes can get really annoying :)

**Comment by cordoval** [comment]
@jwaterfaucett could you please close this ticket since it does support what you want?
