### ISSUE TITLE
Make prefixes translatable aswell

### ISSUE THREAD

**Issue by xyanide** [BeSimple/BeSimpleI18nRoutingBundle#29]
Currently, prefixes cannot be defined with a locale. It would be great if this was possible.

This way we can easily do:

[EN] /your-account/dashboard
[NL] /uw-account/dashboard

#locales:  {en: '/your-account', nl: '/uw-account' }

For example. Now we need to add the prefix with the locales section of the route.

**Comment by boekkooi** [comment]
This was implemented in PR #56 so closing this issue
