### ISSUE TITLE
Other problem

### ISSUE THREAD

**Issue by pdias** [BeSimple/BeSimpleI18nRoutingBundle#38]
Now I have another problem ...

My config:

be_simple_i18n_routing: 
    attribute_translator:
        type: doctrine_dbal
        connection: default
        cache: apc

when I install the bundle ... this error appears:

  [ErrorException]
  Notice: Undefined index: cache in F:\EasyPHP\www\mustamp\vendor\besimple\i1
  8n-routing-bundle\BeSimple\I18nRoutingBundle\DependencyInjection\BeSimpleI1
  8nRoutingExtension.php line 40

Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handl
ing the post-update-cmd event terminated with an exception

  [RuntimeException]
  An error occurred when executing the ""cache:clear --no-warmup"" command.

Thanks,

Paulo

**Comment by boekkooi** [comment]
It looks like that was fixed in adfe34977949f6aa23c1bc4d7ac6aedc53d04901 so I'm closing this one
