### ISSUE TITLE
Error after fresh install

### ISSUE THREAD

**Issue by xmateos** [BeSimple/BeSimpleI18nRoutingBundle#41]
Hey,

I´ve just installed  BeSimpleI18nRoutingBundle and everything has stopped working.
I´m using Symfony 2.0.15. I´ve installed this bundle with following lines in deps file:

[I18nRoutingBundle]
    git=git://github.com/BeSimple/BeSimpleI18nRoutingBundle.git
    target=bundles/BeSimple/I18nRoutingBundle
    version=origin/2.0

Nothing appears in my browser but an error (apparently not related to Symfony) is being shown up, saying "The connection has been reset". Looks like an Apache error, though it´s not. When I disable the bundle, everything starts working again.
This is my deps file (just in case there´s any incompatibility):

[symfony]
    git=http://github.com/symfony/symfony.git
    version=v2.0.15

[twig]
    git=http://github.com/fabpot/Twig.git
    version=v1.8.2

[monolog]
    git=http://github.com/Seldaek/monolog.git
    version=1.0.2

[doctrine-common]
    git=http://github.com/doctrine/common.git
    version=2.1.4

[doctrine-dbal]
    git=http://github.com/doctrine/dbal.git
    version=2.1.7

[doctrine]
    git=http://github.com/doctrine/doctrine2.git
    version=2.1.7

[swiftmailer]
    git=http://github.com/swiftmailer/swiftmailer.git
    version=v4.1.7

[assetic]
    git=http://github.com/kriswallsmith/assetic.git
    version=v1.0.3

[twig-extensions]
    git=http://github.com/fabpot/Twig-extensions.git

[metadata]
    git=http://github.com/schmittjoh/metadata.git
    version=1.0.0

[SensioFrameworkExtraBundle]
    git=http://github.com/sensio/SensioFrameworkExtraBundle.git
    target=/bundles/Sensio/Bundle/FrameworkExtraBundle
    version=origin/2.0

[JMSSecurityExtraBundle]
    git=http://github.com/schmittjoh/JMSSecurityExtraBundle.git
    target=/bundles/JMS/SecurityExtraBundle
    version=origin/1.0.x

[SensioDistributionBundle]
    git=http://github.com/sensio/SensioDistributionBundle.git
    target=/bundles/Sensio/Bundle/DistributionBundle
    version=origin/2.0

[SensioGeneratorBundle]
    git=http://github.com/sensio/SensioGeneratorBundle.git
    target=/bundles/Sensio/Bundle/GeneratorBundle
    version=origin/2.0

[AsseticBundle]
    git=http://github.com/symfony/AsseticBundle.git
    target=/bundles/Symfony/Bundle/AsseticBundle
    version=v1.0.1

[FOSUserBundle]
    git=http://github.com/FriendsOfSymfony/FOSUserBundle.git
    target=bundles/FOS/UserBundle
    version=1.2.0
    
[FOSJsRoutingBundle]
    git=http://github.com/FriendsOfSymfony/FOSJsRoutingBundle.git
    target=/bundles/FOS/JsRoutingBundle
    
[knp-components]
    git=http://github.com/KnpLabs/knp-components.git

[KnpPaginatorBundle]
    git=http://github.com/KnpLabs/KnpPaginatorBundle.git
    target=bundles/Knp/Bundle/PaginatorBundle

Any clue on what can it be happening?

Thanks & Regards,
![error](https://f.cloud.github.com/assets/1507586/276152/2ca898ec-90a4-11e2-8e6d-538b7febf15f.jpg)

**Comment by cordoval** [comment]
this symfony version is no longer supported, please close ticket
