### ISSUE TITLE
Regaring Routes defined in annotations.

### ISSUE THREAD

**Issue by Bharatesh** [BeSimple/BeSimpleI18nRoutingBundle#43]
How to handle routes that are defined as Annotations.

**Comment by mappedinn** [comment]
annotation is available now in the bundle?

**Comment by cordoval** [comment]
:-1: it is not a good idea imo, not fun of huge annotations which this implies

**Comment by mappedinn** [comment]
annotation is really better...

**Comment by mappedinn** [comment]
+1

**Comment by CoalaJoe** [comment]
+1

**Comment by boekkooi** [comment]
Hi all,

So I'm taking a look at how to implemented this and I just want to put down a format for the annotation and get some feedback.
So I propose to make the annotation look as followed:
```PHP
/**
  * @I18nRoute({ "en": "/english/", "nl": "/dutch/"  }, defaults={"page": 1})
  */
```

Are there any people again this or are there better suggestions?

**Comment by HeahDude** [comment]
I love it, but since annotations are for controllers why not simply `@I18n`?
Note that this is trivial as it could simply be done while importing with something like:
```php
use BeSimple\I18nRoutingBundle\Annotation\I18nRoute as I18n;
```

**Comment by boekkooi** [comment]
So if someone want to give annotations a try please use this branch https://github.com/boekkooi/BeSimpleI18nRoutingBundle/tree/issue-43 since I'm waiting for #80 to be merged.

**Comment by mappedinn** [comment]
@boekkooi is it possible to use this annotation with **FOSRestBundle** to build a RESTful API?

**Comment by boekkooi** [comment]
@mappedinn I would expect it to work yes, if not please add a comment to the PR (#81)

**Comment by boekkooi** [comment]
The annotation loader is merged so for anyone interesting use dev-master
