### ISSUE TITLE
Site Url is showing as 1

### ISSUE THREAD

**Issue by kapilfullestop** [BeSimple/BeSimpleI18nRoutingBundle#44]
I am new in Symfony. I am using BeSimpleI18nRoutingBundle to generate the speaking url.
But I am facing a problem in the routing.
I created a routing for registration in English and French. But as I change the site language then it is changing the url as

/1/site_folder/fr/s'inscrire in French and

/1/ site_folder /en/register in English.
But I want it as

example.com/site_folder/en/register for English
example.com/site_folder/fr/ s’inscrire for French

My i18n.yml routing code is as follows

AppsFrontendBundle_register:
locales: { en: "/register", fr: "/s'inscrire" }
defaults: { _controller: AppsFrontendBundle:User:register }
requirements:
_method: GET|POST

So @francisbesset  please help me to solve this problem.

**Comment by cordoval** [comment]
This fork https://github.com/cornsket/BeSimpleI18nRoutingBundle is wrong and has a typo commit and some commits that are very doubtful. :-1:

**Comment by boekkooi** [comment]
I assume this was fixed in PR #50
