### ISSUE TITLE
Need an Example for -> Translating the route attributes

### ISSUE THREAD

**Issue by SOYOS** [BeSimple/BeSimpleI18nRoutingBundle#60]
https://github.com/BeSimple/BeSimpleI18nRoutingBundle#translating-the-route-attributes

Dont understand this Part...... Can i find anywere an example? Normaly i handle translations in twig with:
{{variable|trans}}

Can i handle the attributes with BeSimpleI18nRoutingBundle with the translation files? 

Config.yml:
be_simple_i18n_routing:
    attribute_translator:
        type: translator

messages.en.yml
messages.es.yml

please help me out :-)

And if i use attribute_translatior doctrine i get an error - cache attribute not found.... ok, hope anybody can help me out. In the Internet are no examples from this attribute part - but the rest works very well!

**Comment by christiangh** [comment]
We are going to work with the next example, our website is going to show different animal lists in English and Spanish:

    www.myweb.com/en/animals/dogs.html
    www.myweb.com/es/animales/perros.html
    www.myweb.com/en/animals/cats.html
    www.myweb.com/es/animales/gatos.html

 
Firstly, we have to add the next code to our config.yml:

// app/config/config.yml
#Be simple i12n routing
be_simple_i18n_routing:
    attribute_translator:
        type: translator


After that, we have to create the URL in routing.yml (within the main bundle):

// src/Acme/MyBundle/Resources/config/routing.yml
route_animals:
    locales:  { en: "/en/animals/{type}", es: "/es/animales/{type}" }
    defaults: { _controller: AcmeMyBundle:Default:animals, _translate: "type"}

With the previous code, we have fixied the base URL in English as "/en/animals/" followed by the var "type". The structure for the spanish URL is the same "/es/animales/" followed by "type". We have to add in defaults the vars to translate, in this case: "_translate: 'type'".

Now, we have our route ready and now we are going to create our translation files. The name of these files must be "<route name>_<attribute name>.<lang>.yml", then we will create 2 translation files: route_animals_type.en.yml and route_animals_type.es.yml. These files will be on the translation folder of the main bundle and they will contain a translation per line with the next form <key>: <translation>.

// src/Acme/MyBundle/Resources/translations/route_animals_type.en.yml
dogs: dogs.html
cats: cats.html

// src/Acme/MyBundle/Resources/translations/route_animals_type.es.yml
dogs: perros.html
cats: gatos.html
 

Finally, we can generate URLs including values for all the vars. For example, if we want to create a link to a dog list in English from a Twig template, we will fill in the var locale with the language, type with key and translate with the name of the vars that we want to translate :

// src/Acme/MyBundle/Resources/views/default/view.html.twig
{{ url( "route_animals", {"locale": "en", "type": "dogs", "translate": "type"} ) }}
// link to: www.myweb.com/en/animals/dogs.html

**Comment by malutanpetronel** [comment]
Are you sure this is correct...

// app/config/config.yml
#Be simple i12n routing
be_simple_i18n_routing:
attribute_translator:
type: translator

?

After I added in my config file:

...

        sonata.user.block.menu:    # used to display the menu in profile pages
        sonata.user.block.account: # used to display menu option (login option)
#
#sonata_user:
#    security_acl: true
#    manager_type: orm # can be orm or mongodb

#Be simple i12n routing
be_simple_i18n_routing:
attribute_translator:
type: translator

I did got on a pge in my site (There is no extension able to load the configuration for "attribute_translator" ):

FileLoaderLoadException in FileLoader.php line 125:
There is no extension able to load the configuration for "attribute_translator" (in /vagrant/sf26/site/app/config/config.yml). Looked for namespace "attribute_translator", found "framework", "security", "twig", "monolog", "swiftmailer", "assetic", "doctrine", "sensio_framework_extra", "be_simple_i18n_routing", "sonata_core", "sonata_block", "knp_menu", "debug", "web_profiler", "sensio_distribution" in /vagrant/sf26/site/app/config/config.yml (which is being imported from "/vagrant/sf26/site/app/config/config_dev.yml").

with a routing.yml:

...

main_about_us:
    locales: 
        ro: "/en/{aboutus}"
        en: "/es/{aboutus}"
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    '::aboutus.html.twig'
        _translate: "aboutus"

**Comment by boekkooi** [comment]
@malutanpetronel You are using the wrong indentation for attribute_translator.

It should be:
```YAML
#Be simple i12n routing
be_simple_i18n_routing:
    attribute_translator:
        type: translator
```

@christiangh thanks for the great answer!
