### ISSUE TITLE
All exceptions (even not related to routing) are throw as RouteNotFoundException

### ISSUE THREAD

**Issue by hediharzallah** [BeSimple/BeSimpleI18nRoutingBundle#61]
Any problem that happens in production, will throw the same exception.
When using dev mode, everything is ok and I get my stack trace and I can detect exactely where the problem is coming from.

Exemple from apache error file : 

Uncaught exception 'Symfony\\Component\\Routing\\Exception\\RouteNotFoundException' with message 'I18nRoute "home" (en) does not exist.' in XXX/vendor/besimple/i18n-routing-bundle/BeSimple/I18nRoutingBundle/Routing/Router.php:165\nStack trace:\n#0 XXX/vendor/besimple/i18n-routing-bundle/BeSimple/I18nRoutingBundle/Routing/Router.php(91): BeSimple\\I18nRoutingBundle\\Routing\\Router->generateI18n('home', 'en', Array, false)\n#1 XXX/vendor/symfony/symfony/src/Symfony/Bridge/Twig/Extension/RoutingExtension.php(45): BeSimple\\I18nRoutingBundle\\Routing\\Router->generate('home', Array, false)\n#2 CACHE/prod/twig/5b/d8/f585b977304a70a0c983957cb7793fda88aba2d66f43f823ba1002dbe648.php(233): Symfony\\Bridge\\Twig\\Extension\\RoutingExtension->getPath('home')\n#3 XXX/vendor/twig/twig/lib/Twig/Template.php(144): __TwigTemplate_5bd8f585b977304a70a0c983957cb7793fda88 in XXX/vendor/twig/twig/lib/Twig/Template.php

**Comment by boekkooi** [comment]
Hi @hediharzallah 

I'm unable to currently reproduce this problem, this may have been a cache issue or some other router chain issue to I'm closing this. If the problem still occurs please reopen this issue
