### ISSUE TITLE
translation no longer work after implementing BeSimpleI18nRoutingBundle

### ISSUE THREAD

**Issue by lesterkamelean** [BeSimple/BeSimpleI18nRoutingBundle#62]
Im working on a website with multiple languages. the site translate depending on the locale. after i integratred BeSimpleI18nRoutingBundle the translation no longer work. Can you point me in the right direction so I can fix the issue

**Comment by boekkooi** [comment]
Hi @lesterkamelean 

I hope you where able to fix your issue. If not then please reopen this issue and provide us with some more information like what symfony versions are you using, configuration etc.
