### ISSUE TITLE
Rely to unpersistent _locale

### ISSUE THREAD

**Issue by flo-sch** [BeSimple/BeSimpleI18nRoutingBundle#64]
*This might more be something that I not clearly understand, rather than an issue, but I think it still might be one.*

I use this (great, thanks) routing bundle to translate my routing in english and french (maybe more after).

Here is my routing root :

    # src/Any/AppBundle/Resources/config/routing.yml
    any_app_international:
        resource: "@AnyAppBundle/Resources/config/routing/front.yml"
        prefix: /{_locale}
        type: be_simple_i18n
        requirements:
            _locale: en|fr

    # src/Any/AppBundle/Resources/config/routing/front.yml
    any_app_home:
        locales:
            en: /
            fr: /
        defaults:
            _controller: AnyAppBundle:Home:index
        requirements:
            _method: get

Which gives two different routes :

    en : /en/
    fr : /fr/

As I want my links to rely in the current user  ````_locale````, I use the twig ````path()```` method in my views normally :

    path('any_app_other_page')

Which actually works well.

However, I also have a backend authenticated part, which is not translated (and will not, as it is not really needed).
So I do not have this ````_locale```` prefix for my backend staff, and to be able to change the language, in order to translate the content from the backend, I implement a kernel event listener, as described in the documentation :

http://symfony.com/doc/current/cookbook/session/locale_sticky_session.html

However, since, the path() does not rely anymore to the ````_locale````.
I have to update my views to gives the locale manually :

    path('any_app_other_page', { 'locale': app.request.locale })

But I will have to manually update all my views, and take the risk I forget some links...

So here is my question :
Would it be possible to do something in the custom LocaleListener to avoid having to update the views ?

**Comment by boekkooi** [comment]
@flo-sch Are you sure that you implemented [Locale "Sticky"](http://symfony.com/doc/current/cookbook/session/locale_sticky_session.html) correctly? because the `$request->setLocale($request->getSession()->get('_locale', $this->defaultLocale));` line ensures that the locale is resolved in the [router](https://github.com/BeSimple/BeSimpleI18nRoutingBundle/blob/master/src/Routing/Router.php#L187).
