### ISSUE TITLE
you have a commit with version 2.3.1 but there is no tag

### ISSUE THREAD

**Issue by cordoval** [BeSimple/BeSimpleI18nRoutingBundle#65]
please tag the bug fix number

please :blush: 
![lkuin](https://cloud.githubusercontent.com/assets/328359/7802459/6871faf0-02fb-11e5-98f1-43f4c85c060b.gif)

**Comment by boekkooi** [comment]
Hi @cordoval, It has been a while but I just tagged version [2.4.0-beta1](https://github.com/BeSimple/BeSimpleI18nRoutingBundle/releases/tag/v2.4.0-beta1)

**Comment by cordoval** [comment]
I no longer use this but 👍
