### ISSUE TITLE
Symfony CMF routes not working

### ISSUE THREAD

**Issue by danielanteloagra** [BeSimple/BeSimpleI18nRoutingBundle#71]
When i enable this bundle, my symfony cmf routes stop working saying it's not passing the document as second parameter.

Anyone else had this?

**Comment by boekkooi** [comment]
@danielanteloagra Do you have a sample project that show this problem? If so please let me know so I can try and fix this.

**Comment by boekkooi** [comment]
Hi @danielanteloagra,

Could you please try version 2.4.0-beta1 and see if the problem still occurs?

Thank you!

**Comment by boekkooi** [comment]
I'm closing this one for now since there is no response :smile: 
Still thank you for reporting and please reopen the issue when the problem still occurs.
