### ISSUE TITLE
Exclude language

### ISSUE THREAD

**Issue by jeroenvdgulik** [BeSimple/BeSimpleI18nRoutingBundle#75]
Is there an easy way to disable a specific language. For instance I want to introduce a new language in `dev` but without showing up in `prod`.

**Comment by Mattabile** [comment]
Hi,
It's not a issue of BeSimpleI18nRouting Bundle, it's a Working methodological problem.
DEV/PROD system should not be used as management of two different release (version).
DEV is a development system in test mode or upgrade, Dev is not a release.
Use Subversion or Git and create tags and branches for work.

**Comment by boekkooi** [comment]
@jeroenvdgulik I have to agree with @Mattabile that a language exclusion based on a set environment is probably not a great Idea but as a feature flag/config option this can be useful.

As I see it there are 2 ways of implementing this.

This first way is to override `BeSimple\I18nRoutingBundle\Routing\Router::generateI18n` and check if the locale is enabled, if not then throw a `RouteNotFoundException`. This will mean that the routes for disables locales are known to the router but they are just not used.

A second way is to add a locale filter to `BeSimple\I18nRoutingBundle\Routing\I18nRouteCollectionBuilder` that will allow/disallow the provided locales.

I hope this helps.

**Comment by Sentence** [comment]
@boekkooi, can you give us an example config to setup this FilteredLocaleGenerator thingy?
