### ISSUE TITLE
Symfony3 

### ISSUE THREAD

**Issue by Mattabile** [BeSimple/BeSimpleI18nRoutingBundle#83]
Hello,

In order to change Url (and locale) in Twig template , I used `<a href="{{ path(app.request.get('_route'), app.request.get('_route_params')|merge({'_locale': 'en'})) }}" >`
Work good in Symfony2.7
In Symfony3 if i'm in french locale www.domain.com/**fr**/The-Name-of-My-Page-in-French-Language
when i click for change in english language  my new url change in "www.domain.com/en/The-Name-of My-Page-in-French-Language" , if i click on another page everything becomes ok www.domain.com/**en**/The-Name-of-My-New-Page-in-English, if i change language again in french www.domain.com/**fr**/The-Name-of-My-New-Page-in-English. So I have one a shifting step and after everything becomes ok.
I tried `<a href="{{ path(app.request.get('_route'),{'_locale': 'en'}) }}" >` same issue.
You know that? It's work anyway but the end of Url is false

**Comment by boekkooi** [comment]
Hi @Mattabile,

Try using the [`locale`](https://github.com/BeSimple/BeSimpleI18nRoutingBundle/blob/master/src/Routing/Router.php#L65) parameter instead of `_locale` that should fix your issue.

I hope this helps.

**Comment by Mattabile** [comment]
Hi @boekkooi ,

Good Help

`<a href="{{ path(app.request.get('_route'),{'_locale': 'en','locale':'en'}) }}" >`
_locale to change prefix in Url
locale to get translate Url

Fixed ! Thank you , have a nice day .

**Comment by boekkooi** [comment]
Cheers and have a good one.
