### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by iamthestreets** [BeSimple/BeSimpleI18nRoutingBundle#93]
Hi,

I am leaning towards using your bundle over the other one I found, as it seems yours has been recently maintained. I am having an issue with installing.

Please take a look at the [output](http://pastebin.com/nr1PAXzv) when I run the composer command.

How do I fix the issue?

**Comment by pawellewandowski** [comment]
+1

**Comment by marrek13** [comment]
+1

**Comment by ArnaudTarroux** [comment]
same issue here

**Comment by koryonik** [comment]
Try master branch : 

`composer require besimple/i18n-routing-bundle:dev-master`

**Comment by boekkooi** [comment]
Please use version 2.4 of the bundle.
