### ISSUE TITLE
When v2.4 is going to be marked as stable?

### ISSUE THREAD

**Issue by aistis-** [BeSimple/BeSimpleI18nRoutingBundle#99]
Hi guys, when v2.4 is going to be marked as stable? We already use beta in production for a while :)

**Comment by boekkooi** [comment]
Hi @aistis- thank you for the issue I just marked [2.4.0 as stable](https://github.com/BeSimple/BeSimpleI18nRoutingBundle/releases/tag/v2.4.0)
